apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: INVENTORY_SERVICE_URL
              value: http://inventory-service:8080
            - name: MONGODB_URI
              value: mongodb+srv://cluster0.jqukrp9.mongodb.net/?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority&appName=Cluster0
            - name: MONGO_DB_NAME
              value: order_processing_db
            - name: COLLECTION_NAME
              value: orders
            - name: REDIS_ADDR
              value: queue-service:6379
            - name: STREAM_KEY
              value: orders
            - name: CERT_PATH
              value: /etc/certs/mongodb/cert.pem
          volumeMounts:
            - mountPath: /etc/certs/mongodb
              name: mongodb-cert
              readOnly: true
      volumes:
        - name: mongodb-cert
          secret:
            secretName: mongodb-cert
